### ISSUE TITLE
Wrong example adapter use

### ISSUE THREAD

**Issue by vyper** [hanami/model#314]
In https://github.com/hanami/model#adapter we have an example but I received an error!

# Definitions
```ruby
require 'pg'
require 'hanami/model'
require 'hanami/model/adapters/sql_adapter'

class User
  include Hanami::Entity
  attributes :id, :name
end

class UserRepository
  include Hanami::Repository
end


mapper = Hanami::Model::Mapper.new do
  collection :users do
    entity     User
    repository UserRepository
    attribute :id,   Integer
    attribute :name, String
  end
end

adapter = Hanami::Model::Adapters::SqlAdapter.new(mapper, 'postgres://postgres:postgres@postgres/db_development')
UserRepository.adapter = adapter
```

# Consume
```ruby
> UserRepository.first
Hanami::Model::Mapping::UnmappedCollectionError: Cannot find collection:
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/model/mapper.rb:105:in `collection'
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/model/adapters/implementation.rb:89:in `_mapped_collection'
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/model/adapters/sql_adapter.rb:291:in `_collection'
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/model/adapters/sql_adapter.rb:134:in `query'
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/model/adapters/implementation.rb:65:in `first'
	from /rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-model-0.6.1/lib/hanami/repository.rb:474:in `first'
```

# Using adapter directly work
```ruby
adapter.first(:users)
# => it's ok
```

**Comment by vyper** [comment]
It's necessary add also:

```ruby
UserRepository.collection = :users
```
