### ISSUE TITLE
ROM::SQL::UnknownDBTypeError exception is raised when a PostgreSQL table has an enum column

### ISSUE THREAD

**Issue by Moratorius** [hanami/model#361]
ROM raises `ROM::SQL::UnknownDBTypeError` when it attempts to infer the type for an enum column, which prevents the application from being loaded.

Steps to reproduce:

% hanami new bookshelf --database=postgres
% cd bookshelf
% bundle install
% bundle exec hanami generate migration create_books
```ruby
Hanami::Model.migration do
  change do
    extension :pg_enum
    create_enum :form, %w(novel poem drama short_story novella)

    create_table :books do
      primary_key :id

      column :title,  String, null: false
      column :author, String, null: false
      column :form, :form, null: false

      column :created_at, DateTime, null: false
      column :updated_at, DateTime, null: false
    end
  end
end
```
% bundle exec hanami db prepare
% bundle exec hanami generate model book
% bundle exec hanami console
```
bundler: failed to load command: hanami (/usr/local/var/rbenv/versions/2.3.3/bin/hanami)
ROM::SQL::UnknownDBTypeError: Cannot find corresponding type for form
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:69:in `block in map_type'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:68:in `fetch'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:68:in `map_type'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/extensions/postgres/inferrer.rb:48:in `map_type'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:56:in `build_type'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:45:in `block in call'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:44:in `each'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:44:in `each_with_object'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema/inferrer.rb:44:in `call'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/relation.rb:47:in `block (2 levels) in inherited'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/schema.rb:83:in `finalize!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-sql-0.9.0/lib/rom/sql/schema.rb:24:in `finalize!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:53:in `build_relation'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:25:in `block (2 levels) in run!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:24:in `each'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:24:in `block in run!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/relation_registry.rb:6:in `initialize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:23:in `new'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize/finalize_relations.rb:23:in `run!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize.rb:93:in `load_relations'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/setup/finalize.rb:62:in `run!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/create_container.rb:35:in `finalize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/create_container.rb:13:in `initialize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/create_container.rb:54:in `initialize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/create_container.rb:59:in `new'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rom-2.0.2/lib/rom/create_container.rb:59:in `container'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-model-0.7.0/lib/hanami/model.rb:80:in `load!'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components/components.rb:57:in `block (2 levels) in <module:Components>'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components/component.rb:42:in `call'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:122:in `fetch'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:132:in `fetch_or_store'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:83:in `block in resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:82:in `each'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:82:in `resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components/component.rb:136:in `resolve_requirements'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components/component.rb:34:in `call'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:85:in `block (2 levels) in resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:133:in `block in fetch_or_store'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:122:in `fetch'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/concurrent-ruby-1.0.3/lib/concurrent/map.rb:132:in `fetch_or_store'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:83:in `block in resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:82:in `each'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/components.rb:82:in `resolve'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/command.rb:47:in `initialize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/commands/console.rb:47:in `initialize'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/cli.rb:84:in `new'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/lib/hanami/cli.rb:84:in `console'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  /usr/local/var/rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/hanami-0.9.2/bin/hanami:5:in `<top (required)>'
  /usr/local/var/rbenv/versions/2.3.3/bin/hanami:22:in `load'
  /usr/local/var/rbenv/versions/2.3.3/bin/hanami:22:in `<top (required)>'
```

I tried defining the enum type in the entity's [custom schema](http://hanamirb.org/guides/models/entities/#custom-schema), but it didn't work.
```ruby
class Book < Hanami::Entity
  attributes do
    attribute :id,         Types::Int
    attribute :title,      Types::String
    attribute :author,     Types::String
    attribute :form,       Types::Strict::String.enum('novel', 'poem', 'drama', 'short_story', 'novella')
    attribute :created_at, Types::Time
    attribute :updated_at, Types::Time
  end
end
```

**Comment by solnic** [comment]
bad news: rom-sql schema inference doesn't support enums yet

good news: I'm working on rom-sql actively in December/January, so I'll take care of this. My plan is to release 1.0.0.beta but in this specific case, I'll just push a smaller 0.9.1 release with support for enums so you can easily upgrade without having to bump to the beta release

@jodosha is it now possible to define an explicit relation class for hanami? if yes, then a workaround would be to define that class with an explicit schema

**Comment by solnic** [comment]
I just released rom-0.9.1 with support for inferring enums. Unfortunately there's one caveat - it turned out hanami-model doesn't support additional options to gateways, and we need to configure connection with `:pg_enum` extension in order to make this work. This means we need to extend model DSL with support for something like this:

``` ruby
adapter :sql, ENV['DATABASE_URL'], extensions: %i[pg_enum]
```

This option hash can be simply passed to gateway and things will automagically happen.

**Comment by jodosha** [comment]
@solnic Thanks for taking care of this. 👍 💯 💚 

> is it now possible to define an explicit relation class for hanami?

Not yet.

**Comment by AlfonsoUceda** [comment]
For reference this is the [commit](https://github.com/rom-rb/rom-sql/commit/41561c56bba935b623d7c862d03d97c414f56d76) where `rom-sql` supports enums

**Comment by jodosha** [comment]
I tried to reproduce the problem and it's still there, **even with** `rom-sql-0.9.1`, which shipped the support for PG enums.

/cc @solnic @flash-gordon

**Comment by solnic** [comment]
@jodosha did you enable `pg_enum` extension in sequel connection?

**Comment by jodosha** [comment]
@solnic Nope :sweat_smile: - I confirm it works with the `pg_enum` extension in the sequel connection.

Would you and @Moratorius review this related PR https://github.com/hanami/model/pull/367 that allows to customize the connection? Thanks.

**Comment by flash-gordon** [comment]
I believe we need to add pg_enum to [the list of enabled extensions](https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/gateway.rb#L27). I overlooked this because I had to enable this extension manually for the spec I wrote to prepare the database. I'll add it to master and release-0.9 branches /cc @solnic

**Comment by jodosha** [comment]
@flash-gordon That would be great! :100: I assumed it was already there, that's the reason of the failure described [above](https://github.com/hanami/model/issues/361#issuecomment-270083406).

**Comment by flash-gordon** [comment]
@solnic @jodosha OK, done https://github.com/rom-rb/rom-sql/commit/5c7fb0d583beb1fbddd333eda359ecba08faa7d4 :)

**Comment by jodosha** [comment]
@flash-gordon :green_heart:
