### ISSUE TITLE
key not found: :name  when mapping covers not all fields

### ISSUE THREAD

**Issue by maxlapshin** [hanami/model#463]
I have a table in mysql database:
```
mysql> DESCRIBE `streams`;
+-------------------------+--------------+------+------+---------+-------+
| Field                   | Type         | Null | Key  | Default | Extra |
+-------------------------+--------------+------+------+---------+-------+
| name                    | varchar(255) | YES  |      | NULL    |       |
| title                   | varchar(255) | YES  |      | NULL    |       |
| provider                | varchar(255) | YES  |      | NULL    |       |
| static                  | tinyint(1)   | YES  |      | NULL    |       |
| pulse_off               | tinyint(1)   | YES  |      | NULL    |       |
| position                | bigint(20)   | YES  |      | NULL    |       |
| disabled                | tinyint(1)   | YES  |      | NULL    |       |
| retry_limit             | bigint(20)   | YES  |      | NULL    |       |
...
```

Yes, this table don't have primary key.

I have created streams_repository:

```
class StreamRepository < Hanami::Repository
  mapping do
    attribute :provider, from: :provider
  end
end
```

I have declared here not all fields, only one.

Now I start console:

`$ bundle exec hanami console
key not found: :name`

After digging in code I've found that inside `Hanami::Model::Configuration.load!` there is call to `define_entities_mappings(container, repositories)`  that calls `Hanami::Model::Mapping.translate`:
`@r_attributes.fetch(attribute)`

Here `@r_attributes` have only `{:provider=>:provider}` and field `:name` is requested.

Here is stacktrace from load!:

```
hanami-model-1.1.0/lib/hanami/model/mapping.rb:57:in `fetch'
hanami-model-1.1.0/lib/hanami/model/mapping.rb:57:in `translate'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:107:in `block in build_attributes'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:106:in `each'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:106:in `each_with_object'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:106:in `build_attributes'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:88:in `build'
hanami-model-1.1.0/lib/hanami/model/sql/entity/schema.rb:35:in `initialize'
hanami-model-1.1.0/lib/hanami/model/configuration.rb:108:in `new'
hanami-model-1.1.0/lib/hanami/model/configuration.rb:108:in `block in define_entities_mappings'
hanami-model-1.1.0/lib/hanami/model/configuration.rb:104:in `each'
hanami-model-1.1.0/lib/hanami/model/configuration.rb:104:in `define_entities_mappings'
hanami-model-1.1.0/lib/hanami/model/configuration.rb:144:in `load!'
hanami-model-1.1.0/lib/hanami/model.rb:79:in `load!'
hanami-1.1.0/lib/hanami/components/components.rb:89:in `block (2 levels) in <module:Components>'
hanami-1.1.0/lib/hanami/components/component.rb:44:in `call'
```

So it seems to be a bug: if not all fields from table are declared in mapping, then fetch on hash map is called and exception stops loading all hanami.

**Comment by jodosha** [comment]
@maxlapshin Hi, `mapping` should be used to "translate" database columns into entity attributes. This mechanism expects to act on all the schema columns.

If you want to work only with a subset of the database columns, you must manually define your schema, and not let the repository to automatically infer it:

```ruby
class StreamRepository < Hanami::Repository
  schema do
    attribute :provider, Hanami::Model::Sql::Types::String
  end
end
```
