### ISSUE TITLE
Can't prepare testing PostgreSQL database

### ISSUE THREAD

**Issue by diegotoral** [hanami/model#581]
Hi all!

I'm not sure this is a bug or I've made some mistake.

I am trying to follow the steps in the [Getting Started](https://guides.hanamirb.org/introduction/getting-started/) guide and have setup a basic Docker and docker-compose environment for development (just like I usually do for Rails) but I am stuck on the very beginning of the guide when trying to run `HANAMI_ENV=test bundle exec hanami db prepare`. It fails with the following message and stacktrace.

```
no implicit conversion of nil into String
/usr/local/lib/ruby/2.6.0/open3.rb:213:in `spawn'
	/usr/local/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
	/usr/local/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	/usr/local/bundle/gems/hanami-model-1.3.2/lib/hanami/model/migrator/postgres_adapter.rb:98:in `call_db_command'
	/usr/local/bundle/gems/hanami-model-1.3.2/lib/hanami/model/migrator/postgres_adapter.rb:36:in `create'
	/usr/local/bundle/gems/hanami-model-1.3.2/lib/hanami/model/migrator.rb:287:in `create'
	/usr/local/bundle/gems/hanami-model-1.3.2/lib/hanami/model/migrator.rb:332:in `prepare'
	/usr/local/bundle/gems/hanami-model-1.3.2/lib/hanami/model/migrator.rb:247:in `prepare'
	/usr/local/bundle/gems/hanami-1.3.3/lib/hanami/cli/commands/db/prepare.rb:26:in `prepare_database'
	/usr/local/bundle/gems/hanami-1.3.3/lib/hanami/cli/commands/db/prepare.rb:17:in `call'
	/usr/local/bundle/gems/hanami-1.3.3/lib/hanami/cli/commands/command.rb:85:in `call'
	/usr/local/bundle/gems/hanami-cli-0.3.1/lib/hanami/cli.rb:57:in `call'
	/usr/local/bundle/gems/hanami-1.3.3/bin/hanami:6:in `<top (required)>'
	/usr/local/bundle/bin/hanami:23:in `load'
	/usr/local/bundle/bin/hanami:23:in `<top (required)>'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
	/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
	/usr/local/bundle/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/usr/local/bundle/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
	/usr/local/bundle/bin/bundle:23:in `load'
	/usr/local/bundle/bin/bundle:23:in `<main>'
```

I have the `DATABASE_URL` environment variable set as follow

```
DATABASE_URL=postgres://postgres:postgres@postgres:5432
```

Hanami version is `1.3`

**Comment by jodosha** [comment]
@diegotoral Hi, do you have PG CLI commands installed?

`db prepare` does:

  * drop the database (if existing)
  * create the database
  * run the migrations

For the first two steps, it uses `dropdb` and `createdb` from PG utilities. If you login to your Docker image are you able to find these executables?

```
$ docker run -it --rm <name-of-your-image> /bin/bash
# which createdb
```

**Comment by diegotoral** [comment]
Yes, I forgot to mention that I already checked that. I do have and can connect to postgres using psql.

```
root@ac9bd4ec6bb3:/app# which createdb
/usr/bin/createdb
root@ac9bd4ec6bb3:/app# which dropdb
/usr/bin/dropdb
```

**Comment by cllns** [comment]
@diegotoral It looks like this might be due to having an old version of bundler (2.0.2) Can you run `gem update --system` (with `sudo` if needed). See: https://github.com/rubygems/rubygems/issues/1668 for other possible similar solutions if that doesn't work.

**Comment by diegotoral** [comment]
@cllns @jodosha Thanks for the help but I just figured out the problem... `DATABASE_URL` is missing the database name part! 🤦‍♂️ 😂

**Comment by jodosha** [comment]
@diegotoral Hey, I'm happy that you found the solution to this problem. 😄
